# vim:tw=200
---
mail_accounts:
  - name: 'Personal'
    email: '{{ user_email }}'
    keychain_account: '{{ keychain_account }}'
    keychain_name: '{{ keychain_name }}'
    imap_server: '{{ imap_server }}'
    smtp_server: '{{ smtp_server }}'
    accent: blue
