# vim:tw=200
---
user_email: 'ahmed@miro.com'
mail_accounts:
  - name: 'Work'
    email: '{{ user_email }}'
    keychain_account: '{{ keychain_account }}'
    keychain_name: '{{ keychain_name }}'
    imap_server: '{{ imap_server }}'
    smtp_server: '{{ smtp_server }}'
    accent: yellow
