live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false

[font]
size = 12.0

[font.normal]
family = "PragmataPro Liga"

[font.italic]
family = "PragmataPro Liga"

[font.bold]
family = "PragmataPro Liga"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["--login"]
program = "zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

################################################################################
# Colors
################################################################################
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x969896"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.cursor]
cursor = "0x20bbfc"
text = "0x1d1f21"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x111111"
foreground = "0xc5c8c6"

################################################################################
# Key bindings
################################################################################
[keyboard]
bindings = [
  { key = "Back", chars = "\u007F" },
  { key = "Back", mods = "Alt", chars = "\u001B\u007F" },
  { key = "Copy", action = "Copy" },
  { key = "Delete", chars = "\u001B[3~" },
  { key = "Down", mode = "AppCursor", chars = "\u001BOB" },
  { key = "Down", mode = "~AppCursor", chars = "\u001B[B" },
  { key = "Down", mods = "Alt", chars = "\u001B[1;3B" },
  { key = "Down", mods = "Control", chars = "\u001B[1;5B" },
  { key = "Down", mods = "Shift", chars = "\u001B[1;2B" },
  { key = "End", mode = "AppCursor", chars = "\u001BOF" },
  { key = "End", mode = "~AppCursor", chars = "\u001B[F" },
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Home", mode = "AppCursor", chars = "\u001BOH" },
  { key = "Home", mode = "~AppCursor", chars = "\u001B[H" },
  { key = "Insert", chars = "\u001B[2~" },
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Key6", mods = "Control", chars = "\u001E" },
  { key = "Left", mode = "AppCursor", chars = "\u001BOD" },
  { key = "Left", mode = "~AppCursor", chars = "\u001B[D" },
  { key = "Left", mods = "Alt", chars = "\u001B[1;3D" },
  { key = "Left", mods = "Control", chars = "\u001B[1;5D" },
  { key = "Left", mods = "Shift", chars = "\u001B[1;2D" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "NumpadEnter", chars = """\n\n""" },
  { key = "PageDown", chars = "\u001B[6~" },
  { key = "PageDown", mods = "Control", chars = "\u001B[6;5~" },
  { key = "PageDown", mods = "Shift", chars = "\u001B[6;2~" },
  { key = "PageUp", chars = "\u001B[5~" },
  { key = "PageUp", mods = "Control", chars = "\u001B[5;5~" },
  { key = "PageUp", mods = "Shift", chars = "\u001B[5;2~" },
  { key = "Paste", action = "Paste" },
  { key = "Right", mode = "AppCursor", chars = "\u001BOC" },
  { key = "Right", mode = "~AppCursor", chars = "\u001B[C" },
  { key = "Right", mods = "Alt", chars = "\u001B[1;3C" },
  { key = "Right", mods = "Control", chars = "\u001B[1;5C" },
  { key = "Right", mods = "Shift", chars = "\u001B[1;2C" },
  { key = "Tab", mods = "Shift", chars = "\u001B[Z" },
  { key = "Up", mode = "AppCursor", chars = "\u001BOA" },
  { key = "Up", mode = "~AppCursor", chars = "\u001B[A" },
  { key = "Up", mods = "Alt", chars = "\u001B[1;3A" },
  { key = "Up", mods = "Control", chars = "\u001B[1;5A" },
  { key = "Up", mods = "Shift", chars = "\u001B[1;2A" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "D", mods = "Alt", chars = "\u001Bd" },
  { key = "H", mods = "Command", action = "Hide" },
  { key = "K", mods = "Command", action = "ClearHistory" },
  { key = "K", mods = "Command", chars = "\f" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "T", mods = "Command", chars = "\u0001c" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "W", mods = "Command", chars = "\u0001x" },
  { key = "F1", chars = "\u001BOP" },
  { key = "F1", mods = "Alt", chars = "\u001B[1;6P" },
  { key = "F1", mods = "Command", chars = "\u001B[1;3P" },
  { key = "F1", mods = "Control", chars = "\u001B[1;5P" },
  { key = "F1", mods = "Shift", chars = "\u001B[1;2P" },
  { key = "F2", chars = "\u001BOQ" },
  { key = "F2", mods = "Alt", chars = "\u001B[1;6Q" },
  { key = "F2", mods = "Command", chars = "\u001B[1;3Q" },
  { key = "F2", mods = "Control", chars = "\u001B[1;5Q" },
  { key = "F2", mods = "Shift", chars = "\u001B[1;2Q" },
  { key = "F3", chars = "\u001BOR" },
  { key = "F3", mods = "Alt", chars = "\u001B[1;6R" },
  { key = "F3", mods = "Command", chars = "\u001B[1;3R" },
  { key = "F3", mods = "Control", chars = "\u001B[1;5R" },
  { key = "F3", mods = "Shift", chars = "\u001B[1;2R" },
  { key = "F4", chars = "\u001BOS" },
  { key = "F4", mods = "Alt", chars = "\u001B[1;6S" },
  { key = "F4", mods = "Command", chars = "\u001B[1;3S" },
  { key = "F4", mods = "Control", chars = "\u001B[1;5S" },
  { key = "F4", mods = "Shift", chars = "\u001B[1;2S" },
  { key = "F5", chars = "\u001B[15~" },
  { key = "F5", mods = "Alt", chars = "\u001B[15;6~" },
  { key = "F5", mods = "Command", chars = "\u001B[15;3~" },
  { key = "F5", mods = "Control", chars = "\u001B[15;5~" },
  { key = "F5", mods = "Shift", chars = "\u001B[15;2~" },
  { key = "F6", chars = "\u001B[17~" },
  { key = "F6", mods = "Alt", chars = "\u001B[17;6~" },
  { key = "F6", mods = "Command", chars = "\u001B[17;3~" },
  { key = "F6", mods = "Control", chars = "\u001B[17;5~" },
  { key = "F6", mods = "Shift", chars = "\u001B[17;2~" },
  { key = "F7", chars = "\u001B[18~" },
  { key = "F7", mods = "Alt", chars = "\u001B[18;6~" },
  { key = "F7", mods = "Command", chars = "\u001B[18;3~" },
  { key = "F7", mods = "Control", chars = "\u001B[18;5~" },
  { key = "F7", mods = "Shift", chars = "\u001B[18;2~" },
  { key = "F8", chars = "\u001B[19~" },
  { key = "F8", mods = "Alt", chars = "\u001B[19;6~" },
  { key = "F8", mods = "Command", chars = "\u001B[19;3~" },
  { key = "F8", mods = "Control", chars = "\u001B[19;5~" },
  { key = "F8", mods = "Shift", chars = "\u001B[19;2~" },
  { key = "F9", chars = "\u001B[20~" },
  { key = "F9", mods = "Alt", chars = "\u001B[20;6~" },
  { key = "F9", mods = "Command", chars = "\u001B[20;3~" },
  { key = "F9", mods = "Control", chars = "\u001B[20;5~" },
  { key = "F9", mods = "Shift", chars = "\u001B[20;2~" },
  { key = "F10", chars = "\u001B[21~" },
  { key = "F10", mods = "Alt", chars = "\u001B[21;6~" },
  { key = "F10", mods = "Command", chars = "\u001B[21;3~" },
  { key = "F10", mods = "Control", chars = "\u001B[21;5~" },
  { key = "F10", mods = "Shift", chars = "\u001B[21;2~" },
  { key = "F11", chars = "\u001B[23~" },
  { key = "F11", mods = "Alt", chars = "\u001B[23;6~" },
  { key = "F11", mods = "Command", chars = "\u001B[23;3~" },
  { key = "F11", mods = "Control", chars = "\u001B[23;5~" },
  { key = "F11", mods = "Shift", chars = "\u001B[23;2~" },
  { key = "F12", chars = "\u001B[24~" },
  { key = "F12", mods = "Alt", chars = "\u001B[24;6~" },
  { key = "F12", mods = "Command", chars = "\u001B[24;3~" },
  { key = "F12", mods = "Control", chars = "\u001B[24;5~" },
  { key = "F12", mods = "Shift", chars = "\u001B[24;2~" },
]

[mouse]
bindings = [{ mouse = "Middle", action = "PasteSelection" }]
