#!/usr/bin/env sh

TMUX_WIFI=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ SSID/{print $2}')

[[ -n $TMUX_WIFI ]] && echo "$TMUX_WIFI" || echo '#[fg=red]⨉#[fg=colour237]'
