#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import sys
import os
import time
from datetime import datetime, timedelta
from random import choice

try:
    from urllib.request import urlopen, HTTPError, Request
except ImportError:
    from urllib2 import urlopen, HTTPError
    from urllib2 import Request


RED = "#[fg=red]" if os.environ["TMUX"] else "\033[1;31;40m"
prayers = ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"]
agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1",
    "Mozilla",
]

# https://aladhan.com/prayer-times-api#GetCalendarByCitys
city = sys.argv[1] if len(sys.argv) > 1 else "amsterdam"
country = sys.argv[2] if len(sys.argv) > 2 else "nl"
method = sys.argv[3] if len(sys.argv) > 3 else 12
tune = sys.argv[4] if len(sys.argv) > 4 else "0,-19,0,0,0,0,0,10,0"


def get_data(day_time):
    url = (
        "http://api.aladhan.com/v1/timingsByCity/{time}?method={method}"
        "&city={city}&country={country}&tune={tune}".format(
            city=city,
            country=country,
            method=method,
            tune=tune,
            time=int(time.mktime(day_time.timetuple())),
        )
    )

    try:
        req = Request(url, data=None, headers={"User-Agent": choice(agents)})
        response = urlopen(req)
    except HTTPError as err:
        if err.code == 403:
            print(err)
        else:
            print("Something happened! Error code", err.code)
        return

    data = json.load(response)["data"]

    return {"timings": data["timings"], "readable_date": data["date"]["readable"]}


def get_prayer_time(prayer, readable_date, timings):
    return datetime.strptime(
        "{0} {1}".format(readable_date, timings[prayer]), "%d %b %Y %H:%M"
    )


def print_prayer(now=datetime.now()):
    data = get_data(now)
    timings = data["timings"]
    readable_date = data["readable_date"]

    if get_prayer_time(prayers[-1], readable_date, timings) < now:
        now = now + timedelta(days=1)
        data = get_data(now)
        prayer = prayers[0]

        prayer_time = get_prayer_time(prayer, readable_date, timings)
        now_timestamp = time.mktime(now.timetuple())
        prayer_time_timestamp = time.mktime(prayer_time.timetuple())
        time_remaning = int(prayer_time_timestamp - now_timestamp) / 60

        print(
            "{color}{prayer}: {time}".format(
                prayer=prayer, time=timings[prayer], color=""
            )
        )
        return
    else:

        for prayer in prayers:
            prayer_time = get_prayer_time(prayer, readable_date, timings)
            if prayer_time >= now:
                now_timestamp = time.mktime(now.timetuple())
                prayer_time_timestamp = time.mktime(prayer_time.timetuple())
                time_remaning = int(prayer_time_timestamp - now_timestamp) / 60

                print(
                    "{color}{prayer}: {time}".format(
                        prayer=prayer,
                        time=timings[prayer],
                        color="" if time_remaning > 30 else RED,
                    )
                )
                break


print_prayer()
