---
useTabs: true
singleQuote: true
bracketSpacing: false
proseWrap: 'always'
arrowParens: 'always'
trailingComma: 'all'
semi: false
endOfLine: 'lf'
overrides:
  - files: config/claude/settings.json
    options:
      useTabs: false
      tabWidth: 2
