cask_args appdir: '/Applications'

# cask "1password"
# cask "alfred"
# cask "appcleaner"
cask "arq"
cask "corelocationcli"
cask "db-browser-for-sqlite"
cask "figma"
cask "google-chrome"
# cask "hammerspoon"
cask "imageoptim"
cask "kap"
cask "launchcontrol"
cask "obsidian"
# cask "slack"
cask "sync"
cask "transmit"
cask "virtualbox"
cask "visual-studio-code"
# cask "vscodium"
cask "zoomus"
