#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eueo pipefail

# =======================================================================
# = Helpers & setting some variables
# =======================================================================

DOTFILES_DIR="$HOME/.dotfiles"

tput sgr0
RED=$(tput setaf 1)
ORANGE=$(tput setaf 3)
GREEN=$(tput setaf 2)
PURPLE=$(tput setaf 5)
CYAN=$(tput setaf 4)
BLUE=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)
RESET=$(tput sgr0)

log() {
	local LABEL="[$1]"
	local COLOR="$2"
	shift
	shift
	local MSG=("$@")
	printf "${COLOR}${LABEL}%*s${RESET}" $(($(tput cols) - ${#LABEL})) | tr ' ' '='
	for M in "${MSG[@]}"; do
		let COL=$(tput cols)-2-${#M}
		printf "%s%${COL}s${RESET}" "$COLOR* $M"
	done
	printf "${COLOR}%*s${RESET}\n\n\n" $(tput cols) | tr ' ' '='
}

log_error() {
	log "FAIL" "$RED" "$@"
	exit 1
}

log_info() {
	log "INFO" "$ORANGE" "$@"
}

log_success() {
	log "OK" "$GREEN" "$@"
}

print_main_banner() {
	cd "$HOME"
	command cat <<EOF
$GREEN
                            _       _    __ _ _
                           | |     | |  / _(_) |
                         __| | ___ | |_| |_ _| | ___  ___
                        / _. |/ _ \| __|  _| | |/ _ \/ __|
                       | (_| | (_) | |_| | | | |  __/\__ \ $()
                      (_)__,_|\___/ \__|_| |_|_|\___||___/


$RESET
EOF

	if [ -d "$DOTFILES_DIR/.git" ]; then
		command cat <<EOF
$BLUE
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         $(git --git-dir "$DOTFILES_DIR/.git" --work-tree "$DOTFILES_DIR" log -n 1 --pretty=format:'%C(yellow)commit:  %h')
         $(git --git-dir "$DOTFILES_DIR/.git" --work-tree "$DOTFILES_DIR" log -n 1 --pretty=format:'%C(red)date:    %ad' --date=short)
         $(git --git-dir "$DOTFILES_DIR/.git" --work-tree "$DOTFILES_DIR" log -n 1 --pretty=format:'%C(cyan)author:  %an')
         $(git --git-dir "$DOTFILES_DIR/.git" --work-tree "$DOTFILES_DIR" log -n 1 --pretty=format:'%C(green)message: %s')
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$RESET
EOF
	fi
}

print_prompt() {
	echo "What do you want to do?"
	PS3="Enter your choice (must be a number): "
	options=("All" "Install package manager" "Clone dotfiles" "Backup old files" "Symlink files" "Install Apps" "Change shell" "Quit")
	select opt in "${options[@]}"; do
		case $opt in
		"All")
			all
			break
			;;
		"Install package manager")
			package_manager
			break
			;;
		"Clone dotfiles")
			clone_dotfiles
			break
			;;
		"Install")
			install
			break
			;;
		"Quit")
			break
			;;
		*)
			echo "Invalid option"
			break
			;;
		esac
	done
}

# =======================================================================
# = Main functions
# =======================================================================

install_homebrew() {
	if ! command -v brew >/dev/null; then
		log_success "Installing Homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
}

package_manager() {
	if [ "$(uname)" == "Darwin" ]; then
		xcode-select --install &&
			install_homebrew &&
			true | sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume &&
			source "$HOME/.nix-profile/etc/profile.d/nix.sh"

		if command -v nix-build >/dev/null; then
			nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
			./result/bin/darwin-installer
			# make just installed `darwin-rebuild` command available in current script
			[ -f /etc/static/bashrc ] && source /etc/static/bashrc
		else
			echo "You need to install Nix Darwin https://github.com/LnL7/nix-darwin"
			exit 1
		fi

		if command -v nix-env >/dev/null; then
			nix-env -iA nixpkgs.nixFlakes
		else
			echo "Check your Nix installation, nix-env is not availbe to install nixpkgs.nixFlakes"
			exit 1
		fi

	fi
}

decrypt_repo() {
	cd "$DOTFILES_DIR"

	echo "decrypting dotfiles..."
	echo -n "transcrypt cipher: "
	read -r cipher
	echo -n "transcrypt password: "
	read -sr password
	echo

	transcrypt -c "$cipher" -p "$password"
}

clone_dotfiles() {
	if [[ ! -d $DOTFILES_DIR ]]; then
		log_success "Cloning dotfiles..."
		git clone --recursive https://github.com/ahmedelgabri/dotfiles.git "$DOTFILES_DIR"

		# Setup repo origin & mirrors
		cd "$DOTFILES_DIR" &&
			git remote set-url origin git@github.com:ahmedelgabri/dotfiles.git &&
			git remote add --mirror=push bitbucket git@bitbucket.org:ahmedelgabri/dotfiles.git &&
			git remote add --mirror=push gitlab git@gitlab.com:ahmedelgabri/dotfiles.git

		decrypt_repo
	else
		cd "$DOTFILES_DIR" &&
			git stash -u &&
			git checkout main &&
			git reset --hard origin/main &&
			git submodule update --init --recursive &&
			git checkout - &&
			git stash pop
	fi
}

install() {
	if [ "$(uname)" == "Darwin" ]; then
		sudo mv /etc/shells /etc/shells.old
		sudo mv /etc/zshenv /etc/zshenv.old
		sudo mv /etc/zshrc /etc/zshrc.old
		sudo mv /etc/zprofile /etc/zprofile.old

		cd "$DOTFILES_DIR" &&
			nix --experimental-features 'nix-command flakes' build "./#$(hostname)" &&
			"$DOTFILES_DIR"/result/sw/bin/darwin-rebuild switch --flake "./#$(hostname)"
	else
		sudo nixos-rebuild switch --flake "./#$(hostname)"
	fi
}

all() {
	package_manager
	clone_dotfiles
	install

	FAILED_COMMAND=$(fc -ln -1)

	if [ $? -eq 0 ]; then
		log_success "Done."
		log_info "Don't forget to generate SSH keys & import gpg keys"
		# command vim -u NONE $HOME/.{gitconfig,zshrc}.local
	else
		log_error "Something went wrong, [ Failed on: $FAILED_COMMAND ]"
	fi
}

run() {
	print_main_banner
	print_prompt
}

# =======================================================================
# = Run!
# =======================================================================

run
