#!/usr/bin/env sh

/usr/local/opt/coreutils/libexec/gnubin/timeout 2m /usr/local/bin/mbsync -q -a

find "$HOME/.mail/Personal/INBOX" "$HOME/.mail/Work/INBOX" -type f -mtime -30d -print -exec sh -c 'cat {} | /usr/local/bin/lbdb-fetchaddr' \; 2>/dev/null
