# vim:ft=ruby:

cask_args appdir: '/Applications'

tap "ahmedelgabri/homebrew-battery"
tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "neomutt/homebrew-neomutt"
tap "tavianator/tap"
tap "universal-ctags/universal-ctags"
tap "sachaos/todoist"

# Core
brew "openssl"
brew "git"
brew "python"
brew "python@2" # do I need it anymore?
brew "gawk"
brew "gnu-sed", args: ["with-default-names"]
brew "coreutils"
brew "findutils"
brew "curl"
brew "wget"
brew "pinentry-mac"
brew "gnupg"
brew "zsh"
brew "transcrypt"

# Languages
brew "node"
brew "n"
brew "yarn"
brew "ruby"
cask "java8"
brew "clojure"
brew "leiningen"
brew "candid82/brew/joker"
brew "sbcl" # Lisp
brew "ghc"
brew "cabal-install"
brew "haskell-stack"
brew "pipenv"
# I install rust from https://www.rust-lang.org/en-US/install.html
# check Makefile

# Core utils
brew "hub"
brew "direnv"
brew "fzf"
brew "highlight"
brew "htop"
brew "ncdu"
brew "ripgrep"
brew "pandoc"
brew "urlview"
brew "rename"
brew "z"
brew "tig"
brew "diff-so-fancy"
brew "fd"
brew "jq"
brew "w3m"
brew "cloc"
brew "loc"
brew "tokei"
brew "ranger"
brew "tree"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# Core apps
brew "neovim"
brew "newsboat"
# Mail
brew "isync", args: ["with-berkeley-db"]
brew "lbdb"
brew "msmtp"
brew "offlineimap"
brew "neomutt/homebrew-neomutt/neomutt", args: ["with-gpgme", "with-notmuch-patch", "with-lua"]
# End Mail
brew "mpv", args: ["with-bundle", "with-rubberband"]
brew "rtv"
brew "tmux", args: ["HEAD"]
brew "ahmedelgabri/battery/battery", args: ["HEAD"]
brew "vim", args: ["with-lua", "with-python3", "with-override-system-vi"]
brew "weechat", args: ["with-perl", "with-python", "with-ruby", "with-lua", "with-curl"]
brew "todoist"
brew "youtube-dl"

# Nice to have
# brew "ledger"
brew "graphviz"
brew "asciinema"
brew "editorconfig"
brew "exiftool"
brew "figlet"
brew "heroku"
brew "httpie"
brew "neofetch"
brew "proselint"
brew "task"
brew "tldr"
brew "translate-shell"
brew "bat"
brew "exa"
brew "grc"

cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "arq"
cask "box-sync"
cask "dayone-cli"
cask "keybase"
cask "kitty"
cask "brave-browser"
cask "firefox"
cask "caskroom/versions/firefox-developer-edition"
cask "caskroom/versions/firefox-nightly"
cask "flux"
cask "caskroom/fonts/font-droid-sans-mono-for-powerline"
cask "caskroom/fonts/font-fira-code"
cask "caskroom/fonts/font-hasklig"
cask "caskroom/fonts/font-inconsolata-g-for-powerline"
cask "caskroom/fonts/font-iosevka"
cask "caskroom/fonts/font-meslo-for-powerline"
cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/fonts/font-ibm-plex"
cask "caskroom/fonts/font-symbola"
cask "google-chrome"
cask "caskroom/versions/google-chrome-canary"
# cask "gpg-suite"
cask "hammerspoon"
cask "imageoptim"
cask "iina"
cask "launchcontrol"
cask "licecap"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "rescuetime"
cask "sequel-pro"
cask "sketch"
cask "skype"
cask "transmission"
cask "transmit"
cask "caskroom/versions/visual-studio-code-insiders"
cask "vlc"
cask "viscosity"
cask "webpquicklook"
cask "whatsapp"

# mas "Day One", id: 1055511498
# mas "Guidance", id: 412759995
# mas "Irvue", id: 1039633667
# mas "Keynote", id: 409183694
# mas "Sip", id: 507257563
# mas "The Unarchiver", id: 425424353
# mas "Transmit", id: 403388562
# mas "Tweetbot", id: 557168941
