#!/bin/sh
HOOKS_DIR="$(command git config --get core.hooksPath || echo "$DOTFILES/git/hooks")"
exec "$HOOKS_DIR/ctags" >/dev/null 2>&1 &
[ -f "$GIT_DIR/hooks/post-checkout" ] && exec "$GIT_DIR/hooks/post-checkout" $@
exit 0
