[global]
excludes = ["*.lock", "target"]

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]
