_: {
  imports = [
    ./base/default.nix
    ./darwin/default.nix
    ./darwin/hammerspoon.nix
    ./darwin/karabiner.nix
    ./shared/user-shell.nix
    ./shared/mail.nix
    ./shared/gui.nix
    ./shared/ssh.nix
    ./shared/git.nix
    ./shared/bat.nix
    ./shared/ripgrep.nix
    ./shared/yazi.nix
    ./shared/tmux.nix
    ./shared/vim.nix
    ./shared/ai.nix
    ./shared/ghostty.nix
    ./shared/zk.nix
    ./shared/gpg.nix
    ./shared/kitty.nix
    ./shared/mpv.nix
    ./shared/discord.nix
    ./shared/misc.nix
    ./shared/python.nix
    ./shared/jujutsu.nix
    ./shared/yt-dlp.nix
    ./shared/node.nix
    ./shared/go.nix
    ./shared/rust.nix
    ./shared/agenix.nix
  ];
}
