#!/usr/bin/env bash

FILE="$1"
WIDTH="$2"
HEIGHT="$3"
X="$4"
Y="$5"

case $(file --brief --mime-type "$FILE") in
image/*)
	if [[ -n "$TMUX" ]]; then
		if hash chafa 2>/dev/null; then
			chafa --fill=block --symbols=block --colors=256 --size="$WIDTH"x"$HEIGHT" "$FILE"
		else
			file --brief "$FILE"
		fi
	else
		kitty +kitten icat --stdin=no --transfer-mode=memory --place="${WIDTH}x${HEIGHT}@${X}x${Y}" "$FILE" </dev/null >/dev/tty
		exit 1
	fi
	;;
text/troff)
	man ./ "$1" | col -b
	;;
text/* | */xml | application/json)
	if [[ $FILE == *.md ]]; then
		# Need `-s dark` to force color outside of interactive shell:
		# https://github.com/charmbracelet/glow/issues/440
		glow -s dark --width "$WIDTH" "$FILE"
	else
		bat --style=numbers,changes --terminal-width "$WIDTH" --wrap never --color always "$FILE"
	fi
	;;
application/pdf)
	termpdf.py "$FILE"
	;;
application/zip)
	unzip -l "$FILE"
	;;
application/x-tar | application/gzip)
	tar tf "$FILE"
	;;
*)
	file --brief "$FILE"
	;;
esac
