#!/usr/bin/env bash

# Usage: serve [--directory DIRECTORY] [PORT]
#
# Defaults to port 8000, current directory (ie. will use index.html if present).

if command -v python3 &>/dev/null; then
	python3 -m http.server "$@"
else
	python -m SimpleHTTPServer "$@" || python -m http.server "$@"
fi
