#!/usr/bin/env sh

TMUX_WIFI=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ SSID/{print $2}')

ON_ICON=""
OFF_ICON'⨉'
TAIL="#[fg=colour237] ⦁ "

[ -n "$TMUX_WIFI" ] && echo "$ON_ICON$TMUX_WIFI$TAIL" || echo "#[fg=red]$OFF_ICON$TAIL"
