#!/bin/sh
HOOKS_DIR="$(command git config --get core.hooksPath || echo "~/.dotfiles/templates/git_hooks")"
[ -f "$HOOKS_DIR/ctags" ] && "$HOOKS_DIR/ctags" >/dev/null 2>&1 &
[ -f "$GIT_DIR/hooks/post-checkout" ] && exec "$GIT_DIR/hooks/post-checkout" $@
exit 0
