#!/bin/bash

# https://status.miro.com/api#status
GITHUB_STATUS=$(curl -sS https://trq7m2ycw1t2.statuspage.io/api/v2/status.json | jq -r '.status.indicator')

INDICATIOR="#[fg=colour237]⦁"

case $GITHUB_STATUS in
ma* | cri*)
  STATUS="#[fg=red]   $INDICATOR "
  ;;
mi*)
  STATUS="#[fg=yellow]   $INDICATOR "
  ;;
*)
  STATUS=""
  ;;
esac

printf "%s" "$STATUS"
