# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# For brew-cask
tap phinze/homebrew-cask
tap caskroom/fonts
install brew-cask

# Install GNU core utilities (those that come with OS X are outdated)
install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
# brew install findutils

# Install ZSH 5
install zsh
echo "You need to sudo vim /etc/shells & add this /usr/local/bin/zsh to the end of the file. then run chsh -s /usr/local/bin/zsh"

# Updated rsync
# tap homebrew/dupes
# install rsync

install wget
isntall ack
isntall git
isntall node
isntall tree
isntall dnsmasq
isntall mongodb
isntall phantomjs
isntall hub
isntall rbenv
isntall rbenv-gem-rehash
isntall ruby-build
isntall the_silver_searcher
install macvim --override-system-vim

# Python & work related stuff
install python
install gdal
install geos
install postgis
install postgresql
install proj

# brew-cask tasks
cask install font-inconsolata-dz-for-powerline
cask install font-source-code-pro
cask install dropbox
cask install google-chrome
cask install google-chrome-canary
cask install firefox
cask install firefox-aurora
cask install opera
cask install opera-next
cask install caffeine
cask install alfred
# cask install cloudapp
cask install dash
cask install spectacle
cask install imagealpha
cask install imageoptim
cask install iterm2
cask install macvim
cask install sequel-pro
cask install sublime-text-3
cask install the-unarchiver
cask install sketch
cask install skype
cask install wunderlist
cask install lime-chat
cask install transmit
cask install virtualbox
cask install vlc
cask install hipchat
echo "Put your license in Dash & Sublime. and Install Tweetbot & AppCleaner"

# Remove outdated versions from the cellar
cleanup
