# Make sure we’re using the latest Homebrew
update

# Install GNU core utilities (those that come with OS X are outdated)
install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# Install ZSH 5
install zsh
echo "You need to sudo vim /etc/shells & add this /usr/local/bin/zsh to the end of the file. then run chsh -s /usr/local/bin/zsh"

# Upgrade any already-installed formulae
# upgrade

# homebrew taps taps
tap homebrew/dupes
tap homebrew/versions
tap caskroom/cask
tap caskroom/fonts
tap caskroom/versions

# for sitespeedio
tap sitespeedio/sitespeedio
tap tobli/browsertime

# Install formulas
install caskroom/cask/brew-cask
install wget
install z
install git
install node
install tree
install dnsmasq
install mongodb
install phantomjs
install gh
install rbenv
install rbenv-gem-rehash
install ruby-build
install the_silver_searcher
install macvim --override-system-vim --custom-icons --with-lua
install imagemagick
install nginx
install mysql
install sitespeedio
install todo-txt
install ctags

# Python & work related stuff
install python #2.7.8
echo "to update setuptools & pip run: pip install --upgrade setuptools pip install --upgrade pip"
install gdal #1.11.1
install geos #3.4.2
install postgis #2.1.4
install postgresql #9.3.5
install proj #4.8.0
install elasticsearch-0.20 #0.20.6
install libmemcached #1.0.18
install redis

# Remove outdated versions from the cellar
cleanup
