# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# For brew-cask
tap phinze/homebrew-cask
tap caskroom/fonts
tap caskroom/versions
install brew-cask

# Install GNU core utilities (those that come with OS X are outdated)
install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
# brew install findutils

# Install ZSH 5
install zsh
echo "You need to sudo vim /etc/shells & add this /usr/local/bin/zsh to the end of the file. then run chsh -s /usr/local/bin/zsh"

install wget
install git
install node
install tree
install dnsmasq
install mongodb
install phantomjs
install hub
install rbenv
install rbenv-gem-rehash
install ruby-build
install the_silver_searcher
install macvim --override-system-vim
install imagemagick

# Python & work related stuff
install python
install gdal
install geos
install postgis
install postgresql
install proj

# Remove outdated versions from the cellar
cleanup
