# {{ ansible_managed }}
# vi:syntax=conf

{% for account in mail_accounts %}
[{{ account.name }}]
source            = imaps://{{ account.email | regex_replace('(.*)@(.*)', '\\1%40\\2') }}@{{ account.imap_server }}
source-cred-cmd   = ~/.config/zsh/bin/get-keychain-pass '{{ account.keychain_account }}' '{{ account.keychain_name }}'
outgoing          = smtps+plain://{{ account.email | regex_replace('(.*)@(.*)', '\\1%40\\2') }}@{{ account.smtp_server }}
outgoing-cred-cmd = ~/.config/zsh/bin/get-keychain-pass '{{ account.keychain_account }}' '{{ account.keychain_name }}'
default           = INBOX
from              = {{ user_name }} <{{ account.email }}>
copy-to           = Sent
smtp-starttls     = yes
source            = maildir://~/.mail/{{ account.name }}

{% endfor %}
