#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/script/install | sh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd $HOME
# softwareupdate --verbose --install --all
# xcode-select --install
# xcodebuild -license accept # To accept Xcode EULA


if [[ ! -d "$HOME/.dotfiles" ]]; then
  echo "Clonning dotfiles..."
  mkdir "$HOME/.dotfiles"
  git clone --recursive https://github.com/ahmedelgabri/dotfiles.git "$HOME/.dotfiles"
else
  cd $HOME/.dotfiles && git pull origin master
fi

if [[ ! -d "$HOME/.zprezto" ]]; then
  echo "Clonning prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md\(.N\); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
else
  cd $HOME/.zprezto && git pull && git submodule update --init --recursive
fi

echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Generate SSH keys \for github, bitbucket \& other services you use =====\033[0;0m"
echo "\033[0;34m====== 1- Don't forget to run source ~/.macos & change your zsh to the brew one ====\033[0;0m"
echo "\033[0;34m====== 2- Symlink other dotfiles files from Box Sync													====\033[0;0m"
echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"

if [[ -d "$HOME/.dotfiles" ]]; then
  cd "$HOME/.dotfiles"
else
  echo ".dotfiles directory doesn't exit"
fi

echo "Change your zsh to the brew installed one. and run Make all"

