#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/script/install | sh

set -u

# =======================================================================
# = Helpers & setting some variables
# =======================================================================

DOTFILES_DIR="$HOME/.dotfiles"

tput sgr0
RED=$(tput setaf 1)
ORANGE=$(tput setaf 3)
GREEN=$(tput setaf 2)
PURPLE=$(tput setaf 5)
BLUE=$(tput setaf 4)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)
RESET=$(tput sgr0)

log_error() {
  local MSG="$1"
  let COL=$(tput cols)-2-${#MSG}+${#RESET}

  printf "${RED}%*s${RESET}" $(tput cols) | tr ' ' '='
  printf "%s%${COL}s" "$RED= $MSG" "[FAIL]$RESET"
  printf "${RED}%*s${RESET}" $(tput cols) | tr ' ' '='

  exit 1
}

log_success() {
  local MSG="$1"
  let COL=$(tput cols)-2-${#MSG}+${#RESET}

  printf "${GREEN}%*s${RESET}" $(tput cols) | tr ' ' '='
  printf "%s%${COL}s" "$GREEN= $MSG" "[OK]$RESET"
  printf "${GREEN}%*s${RESET}" $(tput cols) | tr ' ' '='
}

# =======================================================================
# = Main functions
# =======================================================================

install_homebrew() {
  if ! command -v brew >/dev/null; then
    log_success "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install stow
  fi
}

clone_dotfiles() {
  if [[ ! -d $DOTFILES_DIR ]]; then
    log_success "Cloning dotfiles..."
    git clone --recursive https://github.com/ahmedelgabri/dotfiles.git "$DOTFILES_DIR"
  else
    cd "$DOTFILES_DIR" && \
    git stash && \
    git checkout master && \
    git reset --hard origin/master && \
    git submodule update --init --recursive && \
    git checkout - && \
    git stash pop
  fi
}

take_backup() {
  log_success "Taking backups for old files..."

  local BAKCUP_DIR="$HOME/.dotbackup/$(date "+%Y.%m.%d_%H.%M")"
  mkdir -p "$BAKCUP_DIR"

  # @TODO: Look into how to automate this list
  local FILES=(
    ".config/newsboat"
    ".config/nvim"
    ".ctags"
    ".curlrc"
    ".editorconfig"
    ".gemrc"
    ".gitattributes"
    ".gitconfig"
    ".gitignore"
    ".grc"
    ".gvimrc"
    ".hammerspoon"
    ".hushlogin"
    ".ignore"
    ".lbdbrc"
    ".mbsyncrc"
    ".msmtprc"
    ".mutt"
    ".notmuch-config"
    ".pip.conf"
    ".pyrc.py"
    ".terminfo"
    ".tern-config"
    ".tigrc"
    ".tmux.conf"
    ".urlview"
    ".vim"
    ".vimrc"
    ".zlogin"
    ".zprofile"
    ".zshenv"
    ".zshrc"
    "Library/Preferences/com.googlecode.iterm2.plist"
  )

  for file in "${FILES[@]}"; do
    local ITEM="$HOME/$file"

    # [[]] doesn't require quotes around single variables in fact it fails with double quotes around variables
    # https://stackoverflow.com/a/4665080/213124
    if [[ -e $ITEM ]]; then
      echo "Backing up: $ITEM"
      mv "$ITEM" "$BAKCUP_DIR"
    fi
  done
}

symlink_files() {
  log_success "Create some required folders..."

  if [[ ! -d "$HOME/.config" ]]; then
    mkdir $HOME/.config
  fi

  mkdir -p $HOME/.mail/{Personal,Work}

  if [[ -d $DOTFILES_DIR ]]; then
    log_success "Symlinking files/folders..."
    cd "$DOTFILES_DIR" && make symlink
  else
    log_error "There is no $DOTFILES_DIR directory"
  fi
}

install_apps(){
  if [[ -d $DOTFILES_DIR ]]; then
    log_success "Installing apps & tools, this will take a while..."
    cd "$DOTFILES_DIR" && make homebrew
  else
    log_error "There is no $DOTFILES_DIR directory"
  fi
}

change_shell() {
  log_success "Switching shell to (homebrew) zsh..."
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells > /dev/null
  chsh -s "/usr/local/bin/zsh" "$(whoami)"
}

# =======================================================================
# = Run!
# =======================================================================

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd "$HOME"
xcode-select --install

cat <<EOF
$BLUE
                            _       _    __ _ _
                           | |     | |  / _(_) |
                         __| | ___ | |_| |_ _| | ___  ___
                        / _. |/ _ \| __|  _| | |/ _ \/ __|
                       | (_| | (_) | |_| | | | |  __/\__ \ $()
                      (_)__,_|\___/ \__|_| |_|_|\___||___/


                      $RESET~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$BLUE
                      $RESET$BLUE
                      $RESET   $(git log -n 1 --pretty=format:'%C(yellow)commit:  %h') $BLUE
                      $RESET   $(git log -n 1 --pretty=format:'%C(red)date:    %ad' --date=short) $BLUE
                      $RESET   $(git log -n 1 --pretty=format:'%C(cyan)author:  %an') $BLUE
                      $RESET   $(git log -n 1 --pretty=format:'%C(green)message: %s') $BLUE
                      $RESET$BLUE
                      $RESET~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$BLUE
$RESET
EOF


install_homebrew
clone_dotfiles
take_backup
symlink_files
install_apps
change_shell

if [ $? -eq 0 ]; then
  log_success "=========================================================================================================================="
  log_success "Done."
  log_success "Open a new tab & run \"cd ~/.dotfiles && make\" to install node, python packages, iterm2 themes & neovim deps"
  log_success "Don't forget to generate SSH keys & symlink files from box"
  log_success "!!!!! Run transcrypt -c <CIPHER> -p '<PASSWORD' to decrypt encrypted files !!!!!!"
  log_success "=========================================================================================================================="
else
  log_error "=========================================================================================================================="
  log_error "Something went wrong, [ Failed on: $(fc -ln -1) ]"
  log_error "=========================================================================================================================="
fi

