#!/bin/bash

NPM_PACKAGES=(
"jscpd"
"jsctags"
"jsinspect"
"bash-language-server"
"dockerfile-language-server-nodejs"
"flow-language-server"
"javascript-typescript-langserver"
"ocaml-language-server"
"netlify-cli"
"now"
"parker"
"prettier"
"serve"
"source-map-explorer"
"surge"
"svgo"
"overtime-cli"
"rtm-cli"
"dependency-cruiser"
"reason-cli@latest-macos"
"neovim"
)

for package in "${NPM_PACKAGES[@]}"; do
  yarn global add "$package"
done


unset -v NPM_PACKAGES
