#!/bin/bash

PACKAGES=(
"--upgrade setuptools"
"--upgrade pip"
# "markdown"
"vim-vint"
"websocket-client"
"pipenv"
)

for package in "${PACKAGES[@]}"; do
  pip install --user "$package" && pip2 install --user "$package"
done

unset -v PACKAGES
