#!/bin/bash

PACKAGES=(
"setuptools"
"pip"
"vim-vint"
"websocket-client"
"'python-language-server[all]'"
"pipenv"
"vobject" # for mutt & dump-ical.py script
"black"
"pynvim"
)

FLAGS=''

for package in "${PACKAGES[@]}"; do
  [[ $package == "pip" ]] && FLAGS="--upgrade" || FLAGS="--user --upgrade"
  [[ $package == "black" ]] && pip3 install "$FLAGS" "$package" || pip2 install "$FLAGS" "$package" && pip3 install "$FLAGS" "$package"
done

unset -v PACKAGES FLAGS
