#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/script/install | sh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd $HOME
softwareupdate --verbose --install --all
xcode-select --install


if [[ -d "/usr/local" ]]; then
  chown -R $(whoami):admin /usr/local
elif [[ ! -d "/usr/local" ]]; then
  echo "/usr/local doesn't exist, we will try the nice way of creating it"
  mkdir /usr/local && chflags norestricted /usr/local && chown -R $(whoami):admin /usr/local
else
  echo "Tough luck! check here and then run the script again"
  open "https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md#if-usrlocal-does-not-exist"
  exit 1
fi

if [[ ! -d "$HOME/.dotfiles" ]]; then
  echo "Clonning dotfiles..."
  git clone --recursive https://github.com/ahmedelgabri/dotfiles.git $HOME/.dotfiles
else
  cd $HOME/.dotfiles && git pull origin master
fi

if [[ ! -d "$HOME/.zprezto" ]]; then
  echo "Clonning prezto..."
  git clone --recursive https://github.com/ahmedelgabri/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md\(.N\); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
else
  cd $HOME/.zprezto && git pull && git submodule update --init --recursive
fi

echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Generate SSH keys \for github, bitbucket \& other services you use =====\033[0;0m"
echo "\033[0;34m====== Don't forget to run source ~/.osx & change your zsh to the brew one ====\033[0;0m"
echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"

echo "Change your zsh to the brew installed one."
