#!/bin/bash

echo "\033[0;34m------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Cleaning the House. =================================\033[0;0m"
echo "\033[0;34m------------------------------------------------------------\033[0;0m"

FILES=(
  $HOME/.agignore
  $HOME/.gitignore
  $HOME/.gitconfig
  $HOME/.zshrc
  $HOME/.vimrc
  $HOME/.gvimrc
  $HOME/.gemrc
  $HOME/.pythonrc.py
  $HOME/.pip.conf
  $HOME/.hushlogin
  $HOME/.vim
  $HOME/Library/Preferences/com.googlecode.iterm2.plist
)

BAKCUP_DIR=$HOME/.dotbackup/$(date "+%Y-%m-%d_%H:%M")

mkdir -p $BAKCUP_DIR

for file in ${FILES[@]}; do
  if [[ -d "$file" ]]; then
    echo "Backing up directory: $file"
    mv "$file" "$BAKCUP_DIR"
  elif [[ -f "$file" ]]; then
    echo "Backing up file: $file"
    mv "$file" "$BAKCUP_DIR"
  fi
done

echo "\033[0;34m------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Linking... ==========================================\033[0;0m"
echo "\033[0;34m------------------------------------------------------------\033[0;0m"

mkdir -p $HOME/.config
mkdir -p $HOME/.dotfiles/vim/tmp/{swap,undo,view}
mkdir -p $HOME/.mail/{personal,work}

ZSH_FILES=(
  zshrc
  zshenv
  zprofile
  zpreztorc
  zlogin
)

for file in ${ZSH_FILES[@]}; do
  ln -sf $HOME/.dotfiles/zsh/"$file".local $HOME/."$file"
done

ln -sf $HOME/.dotfiles/zsh/hushlogin.local $HOME/.hushlogin
ln -sf $HOME/.dotfiles/ag/agignore.local $HOME/.agignore
ln -sf $HOME/.dotfiles/git/gitignore.local $HOME/.gitignore
ln -sf $HOME/.dotfiles/git/gitconfig.local $HOME/.gitconfig
ln -sf $HOME/.dotfiles/python/pyrc.local $HOME/.pyrc.py
ln -sf $HOME/.dotfiles/python/pip.local $HOME/.pip.conf

ln -sf $HOME/.dotfiles/mail/msmtprc.local $HOME/.msmtprc
ln -sf $HOME/.dotfiles/mail/mbsyncrc.local $HOME/.mbsyncrc
ln -sf $HOME/.dotfiles/mail/lbdbrc.local $HOME/.lbdbrc
ln -sf $HOME/.dotfiles/mail/notmuch-config.local $HOME/.notmuch-config
ln -sf $HOME/.dotfiles/mail/com.ahmedelgabri.isync.plist $HOME/Library/LaunchAgents/com.ahmedelgabri.isync.plist

ln -sf $HOME/.dotfiles/vim/vimrc.local $HOME/.vimrc
ln -sf $HOME/.dotfiles/vim/ $HOME/.vim
ln -sf $HOME/.dotfiles/vim/ $HOME/.config/nvim

ln -sf $HOME/.dotfiles/hammerspoon/ $HOME/.hammerspoon
ln -sf $HOME/.dotfiles/grc/ $HOME/.grc

ln -sf $HOME/.dotfiles/ruby/gemrc.local $HOME/.gemrc
ln -sf $HOME/.dotfiles/iterm2/com.googlecode.iterm2.plist $HOME/Library/Preferences/com.googlecode.iterm2.plist

echo "\033[0;32m------------------------------------------------------------\033[0;0m"
echo "\033[0;32m====== Done. Wohoo! ========================================\033[0;0m"
echo "\033[0;32m------------------------------------------------------------\033[0;0m"

source $HOME/.zshrc
