#!/usr/bin/env sh

__WIFI_NAME=$(wifi)

case $__WIFI_NAME in
Fanko*)
  __LOCATION="Almere"
  ;;
*)
  __LOCATION=""
  ;;
esac

printf "%s#[fg=colour237] ⦁ " "$(curl -s "https://wttr.in/$__LOCATION?format=%l:+%c+%t+%w" 2>/dev/null)"
