#!/usr/bin/env bash

set -Eueo pipefail

FLAKE=${1:-$(hostname -s)}

print_main_banner

# =======================================================================
# = Main functions
# =======================================================================

if xcode-select -p >/dev/null 2>&1; then
	log_info "Xcode already installed"
else
	log_success "Installing Xcode"
	xcode-select --install

	log_success "Installing Rosetta"
	sudo softwareupdate --install-rosetta --agree-to-license
fi

if [ -e "$DOTFILES_DIR/flake.nix" ]; then
	FLAKE_ROOT="$DOTFILES_DIR"
elif [ -n "${BOOTSTRAP_FLAKE_ROOT:-}" ]; then
	FLAKE_ROOT="$BOOTSTRAP_FLAKE_ROOT"
else
	log_error "Could not find a flake source for bootstrap"
fi

log_info "Installing flake -> $FLAKE"
sudo nix --experimental-features 'nix-command flakes' run nix-darwin -- switch --option eval-cache false --flake "$FLAKE_ROOT#$FLAKE"
log_success "$FLAKE installed"

clone_dotfiles

FAILED_COMMAND=$(fc -ln -1)

if [ $? -eq 0 ]; then
	log_success "Done."
	log_info "Don't forget to generate SSH keys & import gpg keys"
else
	log_error "Something went wrong, [ Failed on: $FAILED_COMMAND ]"
fi
