"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
# Default keymaps: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml
[mgr]

prepend_keymap = [
  # (Normally, "Open selected files".)
  # See: https://yazi-rs.github.io/docs/tips#smart-enter
  { on = "o", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },

  # Mnemonic: "[s]how"
  # (Normally, "Search files by name via fd".)
  { on = "s", run = "plugin --sync reveal-in-finder", desc = "Reveal in Finder" },

  # Mnemonic: "[T]oggle preview"
  { on = "T", run = "plugin toggle-pane min-preview", desc = "Hide or show preview" },
  # Mnemonic: "[F]ull-size preview"
  { on = "F", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },

  # https://yazi-rs.github.io/docs/tips#email-selected-files
  { on = "<C-m>", run = 'shell --block -- neomutt -a "$@"', desc = "Attach files to email" },

]
