#!/bin/bash

# https://status.npmjs.org/api#status

CACHE_FILE="$TMPDIR/.tmux-npm-status.tmp"
CACHE_TTL=$((5 * 60)) # 5 minutes

_fetch_status() {
	local status
	status=$(curl -sS --max-time 5 https://wyvgptkd90hm.statuspage.io/api/v2/status.json | jq -r '.status.indicator')
	printf "%s\n%s" "$status" "$(date +'%s')" >"$CACHE_FILE"
	printf "%s" "$status"
}

_get_status() {
	if [[ -f "$CACHE_FILE" ]]; then
		local now epoch delta
		now="$(date +'%s')"
		epoch="$(tail -n 1 "$CACHE_FILE")"
		delta="$((now - epoch))"
		if [[ $delta -gt $CACHE_TTL ]]; then
			_fetch_status
		else
			head -n 1 "$CACHE_FILE"
		fi
	else
		_fetch_status
	fi
}

NPM_STATUS=$(_get_status)

INDICATOR="#[fg=colour237]⦁"
ICON_NPM="$(printf '\uE616')"
ICON_MAINTENANCE="$(printf '\uE20F')"

case $NPM_STATUS in
maj* | cri*)
	STATUS="#[fg=red] ${ICON_NPM}  $INDICATOR "
	;;
mi*)
	STATUS="#[fg=yellow] ${ICON_NPM}  $INDICATOR "
	;;
mai*)
	STATUS="#[fg=yellow] ${ICON_MAINTENANCE}  $INDICATOR "
	;;
*)
	STATUS=""
	;;
esac

printf "%s" "$STATUS"
