#!/usr/bin/env bash

_load_weather() {
	# check for weather command and internet connection
	command -v weather >/dev/null 2>&1 || return 1
	ping -q -c 1 -W 2 1.1.1.1 >/dev/null 2>&1 && {
		weather "" "format=%c+%t+%h+%w+%m" >"$TMP_WEATHER_FILE"
		printf "\n$(date +'%s')" >>"$TMP_WEATHER_FILE"
	}
}

# Weather data
weather_segment() {
	local -r TMP_WEATHER_FILE="$TMPDIR/weather.tmp"
	local -r REFRESH_RATE=$((60 * 60)) # seconds (1 hour)

	[[ -f "$TMP_WEATHER_FILE" ]] || _load_weather

	local now
	now="$(date +'%s')"
	local epoch
	epoch="$(tail -n 1 "$TMP_WEATHER_FILE")"
	local delta
	delta="$((now - epoch))"

	# check if it's time to update the data
	[[ $delta -gt $REFRESH_RATE ]] && _load_weather

	local weather
	weather="$(head -n 1 "$TMP_WEATHER_FILE")"
	weather="$(echo "${weather//+/}")"

	printf "%s" "$weather"
}

weather_segment
