#!/bin/bash

# https://status.miro.com/api#status
MIRO_STATUS=$(curl -sS https://trq7m2ycw1t2.statuspage.io/api/v2/status.json | jq -r '.status.indicator')

INDICATOR="#[fg=colour237]⦁"

case $MIRO_STATUS in
ma* | cri*)
	STATUS="#[fg=red]   $INDICATOR "
	;;
mi*)
	STATUS="#[fg=yellow]   $INDICATOR "
	;;
mai*)
	STATUS="#[fg=yellow]   $INDICATOR "
	;;
*)
	STATUS=""
	;;
esac

printf "%s" "$STATUS"
