#!/bin/bash

# https://www.githubstatus.com/api#status
GITHUB_STATUS=$(curl -sS https://kctbh9vrtdwd.statuspage.io/api/v2/status.json | jq -r '.status.indicator')

INDICATOR="#[fg=colour237]⦁"

case $GITHUB_STATUS in
maj* | cri*)
	STATUS="#[fg=red]   $INDICATOR "
	;;
mi*)
	STATUS="#[fg=yellow]   $INDICATOR "
	;;
mai*)
	STATUS="#[fg=yellow]   $INDICATOR "
	;;
*)
	STATUS=""
	;;
esac

printf "%s" "$STATUS"
