#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/source/install | sh

cd $HOME
# xcode-select --install
git clone --recursive https://github.com/ahmedelgabri/dotfiles.git $HOME/.dotfiles

# Check for Homebrew,
# Install if we don't have it
if ! command -v brew >/dev/null; then
    echo "\033[0;34m------------------------------------------------------------\033[0;0m"
    echo "\033[0;34m====== Installing Homebrew =================================\033[0;0m"
    echo "\033[0;34m------------------------------------------------------------\033[0;0m"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
sh $HOME/.dotfiles/homebrew/homebrew.sh
sh $HOME/.dotfiles/source/setup
# https://github.com/junegunn/vim-plug#usage
# mkdir -p ~/.vim/autoload && curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sh $HOME/.dotfiles/node/packages.sh

rbenv install 2.1.0 && rbenv global 2.1.0
sh $HOME/.dotfiles/ruby/gems.sh

echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Generate SSH keys \for github, bitbucket \& other services you use =====\033[0;0m"
echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"

echo "Run sh localhost.sh from localhost folder to get your virtual hosts working. Run python/packages.sh for Python packages, also change your zsh to the brew installed one."

source $HOME/.osx
