#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/source/install | sh

cd $HOME
# xcode-select --install
git clone https://github.com/ahmedelgabri/dotfiles.git $HOME/.dotfiles
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
brew bundle $HOME/.dotfiles/homebrew/Brewfile
sh $HOME/.dotfiles/node/packages.sh
sh $HOME/.dotfiles/source/setup.sh

rbenv install 2.0.0p-247 && rbenv global 2.0.0p-247
sh $HOME/.dotfiles/ruby/gems.sh

echo "Make sure you generate SSH keys \for github, bitbucket \& other servers you use."
echo "Run sh localhost.sh from localhost folder to get your virtual hosts working."
