#!/bin/bash
# curl -sS https://raw.github.com/ahmedelgabri/dotfiles/master/source/install | sh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd $HOME
softwareupdate --verbose --install --all
xcode-select --install

if [[ ! -d "$HOME/.dotfiles" ]]; then
  git clone --recursive https://github.com/ahmedelgabri/dotfiles.git $HOME/.dotfiles
else
  cd $HOME/.dotfiles && git pull origin master
fi

if [[ ! -d "$HOME/.zprezto" ]]; then
  git clone --recursive https://github.com/ahmedelgabri/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md\(.N\); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
else
  cd $HOME/.zprezto && git pull && git submodule update --init --recursive
fi

# Check for Homebrew,
# Install if we don't have it
if ! command -v brew >/dev/null; then
  echo "\033[0;34m------------------------------------------------------------\033[0;0m"
  echo "\033[0;34m====== Installing Homebrew =================================\033[0;0m"
  echo "\033[0;34m------------------------------------------------------------\033[0;0m"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

sh $HOME/.dotfiles/homebrew/homebrew.sh
sh $HOME/.dotfiles/source/setup
sh $HOME/.dotfiles/node/packages.sh
sh $HOME/.dotfiles/python/packages.sh
sh $HOME/.dotfiles/iterm2/themes.sh


rbenv install 2.1.0 && rbenv global 2.1.0
sh $HOME/.dotfiles/ruby/gems.sh

echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Generate SSH keys \for github, bitbucket \& other services you use =====\033[0;0m"
echo "\033[0;34m====== Don't forget to run source ~/.osx & change your zsh to the brew one ====\033[0;0m"
echo "\033[0;34m-------------------------------------------------------------------------------\033[0;0m"

echo "Change your zsh to the brew installed one."

# source $HOME/.osx
