#!/bin/bash

echo "\033[0;34m------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Cleaning the House. =================================\033[0;0m"
echo "\033[0;34m------------------------------------------------------------\033[0;0m"

rm $HOME/.gitignore
rm $HOME/.gitconfig
rm $HOME/.zshrc
rm $HOME/.vimrc
rm $HOME/.gvimrc
rm $HOME/.gemrc
rm $HOME/.osx
rm $HOME/.pythonrc.py
rm $HOME/.pip.conf
rm $HOME/.hushlogin
rm -rf $HOME/.vim
rm -rf $HOME/Library/Preferences/com.googlecode.iterm2.plist
rm -rf $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

echo "\033[0;34m------------------------------------------------------------\033[0;0m"
echo "\033[0;34m====== Linking... ==========================================\033[0;0m"
echo "\033[0;34m------------------------------------------------------------\033[0;0m"

ln -s $HOME/.dotfiles/zsh/zprezto $HOME/.zprezto

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md\(.N\); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

ln -s $HOME/.dotfiles/zsh/hushlogin.local $HOME/.hushlogin
ln -s $HOME/.dotfiles/git/gitignore.local $HOME/.gitignore
ln -s $HOME/.dotfiles/git/gitconfig.local $HOME/.gitconfig
ln -s $HOME/.dotfiles/osx/osx.local $HOME/.osx
ln -s $HOME/.dotfiles/python/pyrc.local $HOME/.pyrc.py
ln -s $HOME/.dotfiles/python/pip.local $HOME/.pip.conf
ln -s $HOME/.dotfiles/vim/vimrc.local $HOME/.vimrc
ln -s $HOME/.dotfiles/vim/gvimrc.local $HOME/.gvimrc
mkdir $HOME/.dotfiles/vim/.vim
ln -s $HOME/.dotfiles/vim/.vim $HOME/.vim
ln -s $HOME/.dotfiles/ruby/gemrc.local $HOME/.gemrc
ln -s $HOME/.dotfiles/iterm2/com.googlecode.iterm2.plist $HOME/Library/Preferences/com.googlecode.iterm2.plist
ln -s $HOME/.dotfiles/sublime/User $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User


echo "\033[0;32m------------------------------------------------------------\033[0;0m"
echo "\033[0;32m====== Done. Wohoo! ========================================\033[0;0m"
echo "\033[0;32m------------------------------------------------------------\033[0;0m"

source $HOME/.zshrc
